#!/bin/bash

log_file="track.log"

case "$1" in
  start)
    current_time=$(date -u +"%Y-%m-%d %H:%M:%S")
    utc2_time=$(TZ=UTC-2 date +"%Y-%m-%d %H:%M:%S")
    echo "$(date +%s): (${utc2_time}) Start" >> "$log_file"
    ;;
  stop)
    start_time=$(grep -E "^[0-9]+: \([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\) Start$" "$log_file" | tail -1 | cut -d ':' -f1)
    if [ -n "$start_time" ]; then
      end_time=$(date +%s)
      elapsed_time=$((end_time - start_time))
      elapsed_time_formatted=$(printf '%02d:%02d:%02d\n' $((elapsed_time/3600)) $((elapsed_time%3600/60)) $((elapsed_time%60)))
      current_time=$(date -u +"%Y-%m-%d %H:%M:%S")
      utc2_time=$(TZ=UTC-2 date +"%Y-%m-%d %H:%M:%S")
      echo "$(date +%s): (${utc2_time}) Stop (Tracking time: $elapsed_time_formatted)" >> "$log_file"
    else
      echo "No start time found in the log file. Please run 'track start' first."
      exit 1
    fi
    ;;
  *)
    echo "Usage: track [start|stop]"
    exit 1
    ;;
esac

git add "$log_file"
git commit --no-verify -m "Update track log"
git push
